config/routes.rb
RailsBaseApplication::Application.routes.draw do
  resources :oauth_clients

  match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request
  match '/oauth/token',         :to => 'oauth#token',         :as => :token
  match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
  match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
  match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
  match '/oauth',               :to => 'oauth#index',         :as => :oauth

  devise_for :users

  scope '/user', :as => 'user' do
    scope :module => 'private' do
      resources :bitmarks
    end
  end

  resources :short_urls, :only => [:new, :create] do
    # TO DO
  end
  match '/short_urls' => redirect('/')



  # root path application
  root :to => 'home#show'

  # get '/:slug', :to => 'urls#show', :as => 'url'
  constraints DomainConstraint.new('st.pt') do
    match "/:slug", :to => 'marked_urls#show'
  end
end

app/views/shared/layout/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href=root_path) Simple URL Shortener
      .container.nav-collapse
        %ul.nav
          %li= link_to "Home", root_path
          - if user_signed_in?
            %li= link_to 'Bitmarks', user_bitmarks_path
            %li= link_to 'Bundles', '#'
            %li= link_to 'Stats', '#'
        - if user_signed_in?
          %ul.nav.pull-right
            / %li
            /   %a{:href => "#"} Link
            / %li.divider-vertical
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} Profile
                %li
                  %a{:href => "#"} Another action
                %li.divider
                %li
                  = link_to 'Logout', destroy_user_session_path, :method => :delete
        - else
          %ul.nav.pull-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => '#'}
                Welcome to ShortenUrl
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to 'Login', new_user_session_path
                %li
                  = link_to 'Sign Up', new_user_registration_path

app/views/shared/layout/_meta.html.haml
%meta(charset="utf-8")
%meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%title= content_for?(:title) ? yield(:title) : "RailsBaseApplication"
= csrf_meta_tags
/ Le HTML5 shim, for IE6-8 support of HTML elements
/[if lt IE 9]
  = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
= stylesheet_link_tag "application", :media => "all"
%link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
%link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
%link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
%link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
/ %link(href="images/favicon.ico" rel="shortcut icon")